@startuml
title Warm House Devices Component Diagram

left to right direction

!include <C4/C4_Component>

Container_Boundary(system, "Devices") {
  Container(WebApp, "Web Application", "Java, Spring Boot", "Add, remove and update IoT devices")
  ContainerDb(db, "Database", "MongoDB", "Stores devices data")
  ContainerDb(cache, "Cache", "Redis", "Caches devices data")
}

Container(WebApp, "Web Application", "Java, Spring Boot") {
  Component(controller, "DevicesController", "Handles devices management requests")
  Component(service_layer, "Service Layer", "Business logic")
  Component(repository_layer, "Repository Layer", "Data access logic")
}

Rel(controller, service_layer, "Calls business logic")
Rel(service_layer, repository_layer, "Reads/Writes data")
Rel(repository_layer, db, "Reads/Writes devices data")
Rel(repository_layer, cache, "Caches devices data")

@enduml
